language: node_js

# https://github.com/nodejs/LTS
node_js:
  - '7'
  - '6'
  - '4'

git:
  depth: 5

sudo: false

cache: yarn

before_install:
  - npm config set spin false --global

script:
  - if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then npm run lint && npm run check && npm run coverage; else npm run testonly; fi

after_failure:
  - (cd resources; python travis_after_all.py)

after_success:
  - (cd resources; python travis_after_all.py)
  - export $(cat resources/.to_export_back)
  - if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi

deploy:
  - provider: script
    skip_cleanup: true
    script: ./resources/npm-git.sh
    on:
      branch: master
      condition: "$BUILD_LEADER$BUILD_AGGREGATE_STATUS = YESothers_succeeded"
  - provider: npm
    email: "jamesgorman2@gmail.com"
    api_key: "$NPM_KEY"
    on:
      tags: true
      branch: master
      condition: "$BUILD_LEADER$BUILD_AGGREGATE_STATUS = YESothers_succeeded"
